//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public int InventoryID { get; set; }
        public int ProductID { get; set; }
        public string Size { get; set; }
        public Nullable<int> ColorID { get; set; }
        public int InStock { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<SaleItem> SaleItems { get; set; }
    }
}
