//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool Active { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
