//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHS.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.SessionItems = new HashSet<SessionItem>();
        }
    
        public int ServiceID { get; set; }
        public Nullable<int> ServiceTypeID { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool Active { get; set; }
    
        public virtual ServiceType ServiceType { get; set; }
        public virtual ICollection<SessionItem> SessionItems { get; set; }
    }
}
